AWSTemplateFormatVersion: '2010-09-09'
Resources:
  transformGeodataClj:
    Properties:
      CodeUri: s3://davids-lambda-functions/lamda-test-transform-clj.zip
      Handler: lamda_test_transform_clj.stream_handler
      Runtime: java8
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
