version: 0.1

phases:
  pre_build:
    commands:
      - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
      - unzip awscli-bundle.zip
      - sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
  build:
    commands:
      - lein uberjar
      - aws cloudformation package \
        --template-file sam_spec.yml \
        --output-template-file app_spec.yml \
        --s3-bucket davids-lambda-functions

artifacts:
  type: zip
  files:
    - target/lamda-test-transform-clj-0.1.0-SNAPSHOT-standalone.jar
    - app_spec.yml
  discard-paths: yes